name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Tests (Neovim ${{ matrix.neovim }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        neovim: [stable, nightly]
    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim }}

      - name: Run tests
        run: make test
